//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendor.Services.Freightware.UAT.SetCollection
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://namespace.softwareag.com/entirex/xml/mapping", ConfigurationName="Vendor.Services.Freightware.UAT.SetCollection.FWV6WEBPort")]
    public interface FWV6WEBPort
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="SetCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        System.Threading.Tasks.Task<Vendor.Services.Freightware.UAT.SetCollection.SetCollectionResponse> SetCollectionAsync(Vendor.Services.Freightware.UAT.SetCollection.SetCollectionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionInAction
    {
        
        private bool inAddField;
        
        private bool inAddFieldSpecified;
        
        private bool inModifyField;
        
        private bool inModifyFieldSpecified;
        
        private bool inPurgeField;
        
        private bool inPurgeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool InAdd
        {
            get
            {
                return this.inAddField;
            }
            set
            {
                this.inAddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InAddSpecified
        {
            get
            {
                return this.inAddFieldSpecified;
            }
            set
            {
                this.inAddFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool InModify
        {
            get
            {
                return this.inModifyField;
            }
            set
            {
                this.inModifyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InModifySpecified
        {
            get
            {
                return this.inModifyFieldSpecified;
            }
            set
            {
                this.inModifyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool InPurge
        {
            get
            {
                return this.inPurgeField;
            }
            set
            {
                this.inPurgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InPurgeSpecified
        {
            get
            {
                return this.inPurgeFieldSpecified;
            }
            set
            {
                this.inPurgeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionInCollection
    {
        
        private string ordNoField;
        
        private string custCodeField;
        
        private string serviceTypeField;
        
        private string callerNameField;
        
        private string callerRelationshipField;
        
        private string callerSurnameField;
        
        private string callerContactField;
        
        private string collectFromSecurityField;
        
        private string custRefCodeField;
        
        private string dateCancelField;
        
        private string dateCollectionField;
        
        private string extRefNoField;
        
        private string itemMassField;
        
        private string itemQtyField;
        
        private string itemVolField;
        
        private string prePaidAmtField;
        
        private string quoteNoField;
        
        private string reasonCancelledField;
        
        private string[] recInstructionsField;
        
        private string recSiteField;
        
        private SetCollectionInCollectionReceiverInformation receiverInformationField;
        
        private string remarksField;
        
        private string routeIdField;
        
        private string specialInstructionsField;
        
        private string[] sendInstructionsField;
        
        private string sendSiteField;
        
        private SetCollectionInCollectionSenderInformation senderInformationField;
        
        private string timeCollAfterField;
        
        private string timeCollBeforeField;
        
        private string xrefNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrdNo
        {
            get
            {
                return this.ordNoField;
            }
            set
            {
                this.ordNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustCode
        {
            get
            {
                return this.custCodeField;
            }
            set
            {
                this.custCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CallerName
        {
            get
            {
                return this.callerNameField;
            }
            set
            {
                this.callerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CallerRelationship
        {
            get
            {
                return this.callerRelationshipField;
            }
            set
            {
                this.callerRelationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CallerSurname
        {
            get
            {
                return this.callerSurnameField;
            }
            set
            {
                this.callerSurnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CallerContact
        {
            get
            {
                return this.callerContactField;
            }
            set
            {
                this.callerContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CollectFromSecurity
        {
            get
            {
                return this.collectFromSecurityField;
            }
            set
            {
                this.collectFromSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CustRefCode
        {
            get
            {
                return this.custRefCodeField;
            }
            set
            {
                this.custRefCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string DateCancel
        {
            get
            {
                return this.dateCancelField;
            }
            set
            {
                this.dateCancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DateCollection
        {
            get
            {
                return this.dateCollectionField;
            }
            set
            {
                this.dateCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ExtRefNo
        {
            get
            {
                return this.extRefNoField;
            }
            set
            {
                this.extRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ItemMass
        {
            get
            {
                return this.itemMassField;
            }
            set
            {
                this.itemMassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ItemQty
        {
            get
            {
                return this.itemQtyField;
            }
            set
            {
                this.itemQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ItemVol
        {
            get
            {
                return this.itemVolField;
            }
            set
            {
                this.itemVolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PrePaidAmt
        {
            get
            {
                return this.prePaidAmtField;
            }
            set
            {
                this.prePaidAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string QuoteNo
        {
            get
            {
                return this.quoteNoField;
            }
            set
            {
                this.quoteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ReasonCancelled
        {
            get
            {
                return this.reasonCancelledField;
            }
            set
            {
                this.reasonCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] RecInstructions
        {
            get
            {
                return this.recInstructionsField;
            }
            set
            {
                this.recInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string RecSite
        {
            get
            {
                return this.recSiteField;
            }
            set
            {
                this.recSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public SetCollectionInCollectionReceiverInformation ReceiverInformation
        {
            get
            {
                return this.receiverInformationField;
            }
            set
            {
                this.receiverInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string RouteId
        {
            get
            {
                return this.routeIdField;
            }
            set
            {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string SpecialInstructions
        {
            get
            {
                return this.specialInstructionsField;
            }
            set
            {
                this.specialInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] SendInstructions
        {
            get
            {
                return this.sendInstructionsField;
            }
            set
            {
                this.sendInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string SendSite
        {
            get
            {
                return this.sendSiteField;
            }
            set
            {
                this.sendSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public SetCollectionInCollectionSenderInformation SenderInformation
        {
            get
            {
                return this.senderInformationField;
            }
            set
            {
                this.senderInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string TimeCollAfter
        {
            get
            {
                return this.timeCollAfterField;
            }
            set
            {
                this.timeCollAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string TimeCollBefore
        {
            get
            {
                return this.timeCollBeforeField;
            }
            set
            {
                this.timeCollBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string XrefNo
        {
            get
            {
                return this.xrefNoField;
            }
            set
            {
                this.xrefNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionInCollectionReceiverInformation
    {
        
        private string recNameField;
        
        private string recAdd1Field;
        
        private string recAdd2Field;
        
        private string recAdd3Field;
        
        private string recAdd4Field;
        
        private string recAdd5Field;
        
        private string recContactField;
        
        private string recFaxNoField;
        
        private string recTelNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RecName
        {
            get
            {
                return this.recNameField;
            }
            set
            {
                this.recNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RecAdd1
        {
            get
            {
                return this.recAdd1Field;
            }
            set
            {
                this.recAdd1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RecAdd2
        {
            get
            {
                return this.recAdd2Field;
            }
            set
            {
                this.recAdd2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RecAdd3
        {
            get
            {
                return this.recAdd3Field;
            }
            set
            {
                this.recAdd3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string RecAdd4
        {
            get
            {
                return this.recAdd4Field;
            }
            set
            {
                this.recAdd4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string RecAdd5
        {
            get
            {
                return this.recAdd5Field;
            }
            set
            {
                this.recAdd5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RecContact
        {
            get
            {
                return this.recContactField;
            }
            set
            {
                this.recContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string RecFaxNo
        {
            get
            {
                return this.recFaxNoField;
            }
            set
            {
                this.recFaxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string RecTelNo
        {
            get
            {
                return this.recTelNoField;
            }
            set
            {
                this.recTelNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionInCollectionSenderInformation
    {
        
        private string senNameField;
        
        private string senAdd1Field;
        
        private string senAdd2Field;
        
        private string senAdd3Field;
        
        private string senAdd4Field;
        
        private string senAdd5Field;
        
        private string senContactField;
        
        private string senFaxNoField;
        
        private string senTelNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SenName
        {
            get
            {
                return this.senNameField;
            }
            set
            {
                this.senNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SenAdd1
        {
            get
            {
                return this.senAdd1Field;
            }
            set
            {
                this.senAdd1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SenAdd2
        {
            get
            {
                return this.senAdd2Field;
            }
            set
            {
                this.senAdd2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SenAdd3
        {
            get
            {
                return this.senAdd3Field;
            }
            set
            {
                this.senAdd3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SenAdd4
        {
            get
            {
                return this.senAdd4Field;
            }
            set
            {
                this.senAdd4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenAdd5
        {
            get
            {
                return this.senAdd5Field;
            }
            set
            {
                this.senAdd5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SenContact
        {
            get
            {
                return this.senContactField;
            }
            set
            {
                this.senContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SenFaxNo
        {
            get
            {
                return this.senFaxNoField;
            }
            set
            {
                this.senFaxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SenTelNo
        {
            get
            {
                return this.senTelNoField;
            }
            set
            {
                this.senTelNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionResponseCollection
    {
        
        private string ordNoField;
        
        private string custCodeField;
        
        private string custNameField;
        
        private string branchField;
        
        private string branchNameField;
        
        private string serviceTypeField;
        
        private string serviceTypeNameField;
        
        private decimal statusIndField;
        
        private bool statusIndFieldSpecified;
        
        private string statusNameField;
        
        private string branchOrigField;
        
        private string callerContactField;
        
        private string callerNameField;
        
        private string callerRelationshipField;
        
        private string callerSurnameField;
        
        private string collectFromSecurityField;
        
        private string companyCodeField;
        
        private string custCoCodeField;
        
        private string custRefCodeField;
        
        private decimal dateCancelField;
        
        private bool dateCancelFieldSpecified;
        
        private decimal dateCaptureField;
        
        private bool dateCaptureFieldSpecified;
        
        private decimal dateOrderField;
        
        private bool dateOrderFieldSpecified;
        
        private decimal dateCollectionField;
        
        private bool dateCollectionFieldSpecified;
        
        private decimal dateRecvdField;
        
        private bool dateRecvdFieldSpecified;
        
        private string extRefNoField;
        
        private string idAuthField;
        
        private string idCaptureField;
        
        private string idModifyField;
        
        private decimal itemMassField;
        
        private bool itemMassFieldSpecified;
        
        private decimal itemQtyField;
        
        private bool itemQtyFieldSpecified;
        
        private decimal itemVolField;
        
        private bool itemVolFieldSpecified;
        
        private string massUnitField;
        
        private string collectionNoField;
        
        private decimal prePaidAmtField;
        
        private bool prePaidAmtFieldSpecified;
        
        private string quoteNoField;
        
        private string reasonCancelledField;
        
        private string[] recInstructionsField;
        
        private string recSiteField;
        
        private SetCollectionResponseCollectionReceiverInformation receiverInformationField;
        
        private string remarksField;
        
        private string retReasonField;
        
        private string routeIdField;
        
        private string satDelivField;
        
        private string[] sendInstructionsField;
        
        private string sendSiteField;
        
        private SetCollectionResponseCollectionSenderInformation senderInformationField;
        
        private string sourceOfRecField;
        
        private string timeCancelledField;
        
        private decimal timeCapturedField;
        
        private bool timeCapturedFieldSpecified;
        
        private string timeCollAfterField;
        
        private string timeCollBeforeField;
        
        private decimal timeRecvdField;
        
        private bool timeRecvdFieldSpecified;
        
        private decimal totalValueField;
        
        private bool totalValueFieldSpecified;
        
        private string userCancelledField;
        
        private string userRecvdField;
        
        private string waybillNoField;
        
        private decimal valDeclaredField;
        
        private bool valDeclaredFieldSpecified;
        
        private decimal vatField;
        
        private bool vatFieldSpecified;
        
        private string xrefNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrdNo
        {
            get
            {
                return this.ordNoField;
            }
            set
            {
                this.ordNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustCode
        {
            get
            {
                return this.custCodeField;
            }
            set
            {
                this.custCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CustName
        {
            get
            {
                return this.custNameField;
            }
            set
            {
                this.custNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Branch
        {
            get
            {
                return this.branchField;
            }
            set
            {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BranchName
        {
            get
            {
                return this.branchNameField;
            }
            set
            {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ServiceTypeName
        {
            get
            {
                return this.serviceTypeNameField;
            }
            set
            {
                this.serviceTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal StatusInd
        {
            get
            {
                return this.statusIndField;
            }
            set
            {
                this.statusIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusIndSpecified
        {
            get
            {
                return this.statusIndFieldSpecified;
            }
            set
            {
                this.statusIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string StatusName
        {
            get
            {
                return this.statusNameField;
            }
            set
            {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BranchOrig
        {
            get
            {
                return this.branchOrigField;
            }
            set
            {
                this.branchOrigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CallerContact
        {
            get
            {
                return this.callerContactField;
            }
            set
            {
                this.callerContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CallerName
        {
            get
            {
                return this.callerNameField;
            }
            set
            {
                this.callerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CallerRelationship
        {
            get
            {
                return this.callerRelationshipField;
            }
            set
            {
                this.callerRelationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CallerSurname
        {
            get
            {
                return this.callerSurnameField;
            }
            set
            {
                this.callerSurnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CollectFromSecurity
        {
            get
            {
                return this.collectFromSecurityField;
            }
            set
            {
                this.collectFromSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CompanyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string CustCoCode
        {
            get
            {
                return this.custCoCodeField;
            }
            set
            {
                this.custCoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CustRefCode
        {
            get
            {
                return this.custRefCodeField;
            }
            set
            {
                this.custRefCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal DateCancel
        {
            get
            {
                return this.dateCancelField;
            }
            set
            {
                this.dateCancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCancelSpecified
        {
            get
            {
                return this.dateCancelFieldSpecified;
            }
            set
            {
                this.dateCancelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal DateCapture
        {
            get
            {
                return this.dateCaptureField;
            }
            set
            {
                this.dateCaptureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCaptureSpecified
        {
            get
            {
                return this.dateCaptureFieldSpecified;
            }
            set
            {
                this.dateCaptureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal DateOrder
        {
            get
            {
                return this.dateOrderField;
            }
            set
            {
                this.dateOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOrderSpecified
        {
            get
            {
                return this.dateOrderFieldSpecified;
            }
            set
            {
                this.dateOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal DateCollection
        {
            get
            {
                return this.dateCollectionField;
            }
            set
            {
                this.dateCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCollectionSpecified
        {
            get
            {
                return this.dateCollectionFieldSpecified;
            }
            set
            {
                this.dateCollectionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public decimal DateRecvd
        {
            get
            {
                return this.dateRecvdField;
            }
            set
            {
                this.dateRecvdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateRecvdSpecified
        {
            get
            {
                return this.dateRecvdFieldSpecified;
            }
            set
            {
                this.dateRecvdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string ExtRefNo
        {
            get
            {
                return this.extRefNoField;
            }
            set
            {
                this.extRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string IdAuth
        {
            get
            {
                return this.idAuthField;
            }
            set
            {
                this.idAuthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string IdCapture
        {
            get
            {
                return this.idCaptureField;
            }
            set
            {
                this.idCaptureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string IdModify
        {
            get
            {
                return this.idModifyField;
            }
            set
            {
                this.idModifyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public decimal ItemMass
        {
            get
            {
                return this.itemMassField;
            }
            set
            {
                this.itemMassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemMassSpecified
        {
            get
            {
                return this.itemMassFieldSpecified;
            }
            set
            {
                this.itemMassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal ItemQty
        {
            get
            {
                return this.itemQtyField;
            }
            set
            {
                this.itemQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemQtySpecified
        {
            get
            {
                return this.itemQtyFieldSpecified;
            }
            set
            {
                this.itemQtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal ItemVol
        {
            get
            {
                return this.itemVolField;
            }
            set
            {
                this.itemVolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemVolSpecified
        {
            get
            {
                return this.itemVolFieldSpecified;
            }
            set
            {
                this.itemVolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string MassUnit
        {
            get
            {
                return this.massUnitField;
            }
            set
            {
                this.massUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string CollectionNo
        {
            get
            {
                return this.collectionNoField;
            }
            set
            {
                this.collectionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public decimal PrePaidAmt
        {
            get
            {
                return this.prePaidAmtField;
            }
            set
            {
                this.prePaidAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrePaidAmtSpecified
        {
            get
            {
                return this.prePaidAmtFieldSpecified;
            }
            set
            {
                this.prePaidAmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string QuoteNo
        {
            get
            {
                return this.quoteNoField;
            }
            set
            {
                this.quoteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string ReasonCancelled
        {
            get
            {
                return this.reasonCancelledField;
            }
            set
            {
                this.reasonCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] RecInstructions
        {
            get
            {
                return this.recInstructionsField;
            }
            set
            {
                this.recInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string RecSite
        {
            get
            {
                return this.recSiteField;
            }
            set
            {
                this.recSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public SetCollectionResponseCollectionReceiverInformation ReceiverInformation
        {
            get
            {
                return this.receiverInformationField;
            }
            set
            {
                this.receiverInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string RetReason
        {
            get
            {
                return this.retReasonField;
            }
            set
            {
                this.retReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string RouteId
        {
            get
            {
                return this.routeIdField;
            }
            set
            {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string SatDeliv
        {
            get
            {
                return this.satDelivField;
            }
            set
            {
                this.satDelivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] SendInstructions
        {
            get
            {
                return this.sendInstructionsField;
            }
            set
            {
                this.sendInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string SendSite
        {
            get
            {
                return this.sendSiteField;
            }
            set
            {
                this.sendSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public SetCollectionResponseCollectionSenderInformation SenderInformation
        {
            get
            {
                return this.senderInformationField;
            }
            set
            {
                this.senderInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string SourceOfRec
        {
            get
            {
                return this.sourceOfRecField;
            }
            set
            {
                this.sourceOfRecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string TimeCancelled
        {
            get
            {
                return this.timeCancelledField;
            }
            set
            {
                this.timeCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public decimal TimeCaptured
        {
            get
            {
                return this.timeCapturedField;
            }
            set
            {
                this.timeCapturedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeCapturedSpecified
        {
            get
            {
                return this.timeCapturedFieldSpecified;
            }
            set
            {
                this.timeCapturedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string TimeCollAfter
        {
            get
            {
                return this.timeCollAfterField;
            }
            set
            {
                this.timeCollAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string TimeCollBefore
        {
            get
            {
                return this.timeCollBeforeField;
            }
            set
            {
                this.timeCollBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public decimal TimeRecvd
        {
            get
            {
                return this.timeRecvdField;
            }
            set
            {
                this.timeRecvdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeRecvdSpecified
        {
            get
            {
                return this.timeRecvdFieldSpecified;
            }
            set
            {
                this.timeRecvdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public decimal TotalValue
        {
            get
            {
                return this.totalValueField;
            }
            set
            {
                this.totalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalValueSpecified
        {
            get
            {
                return this.totalValueFieldSpecified;
            }
            set
            {
                this.totalValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string UserCancelled
        {
            get
            {
                return this.userCancelledField;
            }
            set
            {
                this.userCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string UserRecvd
        {
            get
            {
                return this.userRecvdField;
            }
            set
            {
                this.userRecvdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public decimal ValDeclared
        {
            get
            {
                return this.valDeclaredField;
            }
            set
            {
                this.valDeclaredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValDeclaredSpecified
        {
            get
            {
                return this.valDeclaredFieldSpecified;
            }
            set
            {
                this.valDeclaredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public decimal Vat
        {
            get
            {
                return this.vatField;
            }
            set
            {
                this.vatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatSpecified
        {
            get
            {
                return this.vatFieldSpecified;
            }
            set
            {
                this.vatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string XrefNo
        {
            get
            {
                return this.xrefNoField;
            }
            set
            {
                this.xrefNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionResponseCollectionReceiverInformation
    {
        
        private string recNameField;
        
        private string recAdd1Field;
        
        private string recAdd2Field;
        
        private string recAdd3Field;
        
        private string recAdd4Field;
        
        private string recAdd5Field;
        
        private string recContactField;
        
        private string recFaxNoField;
        
        private string recTelNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RecName
        {
            get
            {
                return this.recNameField;
            }
            set
            {
                this.recNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RecAdd1
        {
            get
            {
                return this.recAdd1Field;
            }
            set
            {
                this.recAdd1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RecAdd2
        {
            get
            {
                return this.recAdd2Field;
            }
            set
            {
                this.recAdd2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RecAdd3
        {
            get
            {
                return this.recAdd3Field;
            }
            set
            {
                this.recAdd3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string RecAdd4
        {
            get
            {
                return this.recAdd4Field;
            }
            set
            {
                this.recAdd4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string RecAdd5
        {
            get
            {
                return this.recAdd5Field;
            }
            set
            {
                this.recAdd5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RecContact
        {
            get
            {
                return this.recContactField;
            }
            set
            {
                this.recContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string RecFaxNo
        {
            get
            {
                return this.recFaxNoField;
            }
            set
            {
                this.recFaxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string RecTelNo
        {
            get
            {
                return this.recTelNoField;
            }
            set
            {
                this.recTelNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class SetCollectionResponseCollectionSenderInformation
    {
        
        private string senNameField;
        
        private string senAdd1Field;
        
        private string senAdd2Field;
        
        private string senAdd3Field;
        
        private string senAdd4Field;
        
        private string senAdd5Field;
        
        private string senContactField;
        
        private string senFaxNoField;
        
        private string senTelNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SenName
        {
            get
            {
                return this.senNameField;
            }
            set
            {
                this.senNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SenAdd1
        {
            get
            {
                return this.senAdd1Field;
            }
            set
            {
                this.senAdd1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SenAdd2
        {
            get
            {
                return this.senAdd2Field;
            }
            set
            {
                this.senAdd2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SenAdd3
        {
            get
            {
                return this.senAdd3Field;
            }
            set
            {
                this.senAdd3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SenAdd4
        {
            get
            {
                return this.senAdd4Field;
            }
            set
            {
                this.senAdd4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SenAdd5
        {
            get
            {
                return this.senAdd5Field;
            }
            set
            {
                this.senAdd5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SenContact
        {
            get
            {
                return this.senContactField;
            }
            set
            {
                this.senContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SenFaxNo
        {
            get
            {
                return this.senFaxNoField;
            }
            set
            {
                this.senFaxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SenTelNo
        {
            get
            {
                return this.senTelNoField;
            }
            set
            {
                this.senTelNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCollection", WrapperNamespace="urn:com-softwareag-entirex-rpc:FWV6WEB", IsWrapped=true)]
    public partial class SetCollectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InCustCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InRequestCtr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IOSessionData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vendor.Services.Freightware.UAT.SetCollection.SetCollectionInAction InAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vendor.Services.Freightware.UAT.SetCollection.SetCollectionInCollection InCollection;
        
        public SetCollectionRequest()
        {
        }
        
        public SetCollectionRequest(string InUserId, string InPassword, string InCustCode, string InRequestCtr, string IOSessionData, Vendor.Services.Freightware.UAT.SetCollection.SetCollectionInAction InAction, Vendor.Services.Freightware.UAT.SetCollection.SetCollectionInCollection InCollection)
        {
            this.InUserId = InUserId;
            this.InPassword = InPassword;
            this.InCustCode = InCustCode;
            this.InRequestCtr = InRequestCtr;
            this.IOSessionData = IOSessionData;
            this.InAction = InAction;
            this.InCollection = InCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCollectionResponse", WrapperNamespace="urn:com-softwareag-entirex-rpc:FWV6WEB", IsWrapped=true)]
    public partial class SetCollectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IOSessionData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCtr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:FWV6WEB", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vendor.Services.Freightware.UAT.SetCollection.SetCollectionResponseCollection Collection;
        
        public SetCollectionResponse()
        {
        }
        
        public SetCollectionResponse(string IOSessionData, string ReturnCtr, string ReturnCode, string ReturnMessage, Vendor.Services.Freightware.UAT.SetCollection.SetCollectionResponseCollection Collection)
        {
            this.IOSessionData = IOSessionData;
            this.ReturnCtr = ReturnCtr;
            this.ReturnCode = ReturnCode;
            this.ReturnMessage = ReturnMessage;
            this.Collection = Collection;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface FWV6WEBPortChannel : Vendor.Services.Freightware.UAT.SetCollection.FWV6WEBPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FWV6WEBPortClient : System.ServiceModel.ClientBase<Vendor.Services.Freightware.UAT.SetCollection.FWV6WEBPort>, Vendor.Services.Freightware.UAT.SetCollection.FWV6WEBPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FWV6WEBPortClient(EndpointConfiguration endpointConfiguration) : 
                base(FWV6WEBPortClient.GetBindingForEndpoint(endpointConfiguration), FWV6WEBPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FWV6WEBPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FWV6WEBPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FWV6WEBPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FWV6WEBPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FWV6WEBPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Freightware.UAT.SetCollection.SetCollectionResponse> SetCollectionAsync(Vendor.Services.Freightware.UAT.SetCollection.SetCollectionRequest request)
        {
            return base.Channel.SetCollectionAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP12Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP11Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP12Port))
            {
                return new System.ServiceModel.EndpointAddress("http://triton-fw.clients.dovetail.co.za:8180/FreightWareV6Test/services/SetCollec" +
                        "tion.FWV6WEBSOAP12Port/");
            }
            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP11Port))
            {
                return new System.ServiceModel.EndpointAddress("http://triton-fw.clients.dovetail.co.za:8180/FreightWareV6Test/services/SetCollec" +
                        "tion.FWV6WEBSOAP11Port/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FWV6WEBSOAP12Port,
            
            FWV6WEBSOAP11Port,
        }
    }
}
