//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Vendor.Services.Freightware.PROD.GetAccountRateList
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://namespace.softwareag.com/entirex/xml/mapping", ConfigurationName = "Vendor.Services.Freightware.PROD.GetAccountRateList.FWV6WEBPort")]
    public interface FWV6WEBPort
    {

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "GetAccountRateList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<GetAccountRateListResponse> GetAccountRateListAsync(
            GetAccountRateListRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class GetAccountRateListSequence
    {

        private bool byAccountCodeField;

        private bool byAccountCodeFieldSpecified;

        private bool byAccountCodeRateField;

        private bool byAccountCodeRateFieldSpecified;

        private bool byServiceAccountDateEffField;

        private bool byServiceAccountDateEffFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool ByAccountCode
        {
            get { return this.byAccountCodeField; }
            set { this.byAccountCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ByAccountCodeSpecified
        {
            get { return this.byAccountCodeFieldSpecified; }
            set { this.byAccountCodeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public bool ByAccountCodeRate
        {
            get { return this.byAccountCodeRateField; }
            set { this.byAccountCodeRateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ByAccountCodeRateSpecified
        {
            get { return this.byAccountCodeRateFieldSpecified; }
            set { this.byAccountCodeRateFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public bool ByServiceAccountDateEff
        {
            get { return this.byServiceAccountDateEffField; }
            set { this.byServiceAccountDateEffField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ByServiceAccountDateEffSpecified
        {
            get { return this.byServiceAccountDateEffFieldSpecified; }
            set { this.byServiceAccountDateEffFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class GetAccountRateListStartValues
    {

        private string inAccountCodeField;

        private string inActiveRateIndField;

        private string inDateEffectiveField;

        private string inServiceTypeField;

        private string inRateTypeField;

        private string inProductTypeField;

        private string inAreaFromField;

        private string inAreaToField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string InAccountCode
        {
            get { return this.inAccountCodeField; }
            set { this.inAccountCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string InActiveRateInd
        {
            get { return this.inActiveRateIndField; }
            set { this.inActiveRateIndField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string InDateEffective
        {
            get { return this.inDateEffectiveField; }
            set { this.inDateEffectiveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string InServiceType
        {
            get { return this.inServiceTypeField; }
            set { this.inServiceTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string InRateType
        {
            get { return this.inRateTypeField; }
            set { this.inRateTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string InProductType
        {
            get { return this.inProductTypeField; }
            set { this.inProductTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string InAreaFrom
        {
            get { return this.inAreaFromField; }
            set { this.inAreaFromField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string InAreaTo
        {
            get { return this.inAreaToField; }
            set { this.inAreaToField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class GetAccountRateListResponseAccountRateOutput
    {

        private string companyCodeField;

        private string custCodeField;

        private string serviceTypeField;

        private string rateTypeField;

        private string prodTypeField;

        private string areaFromField;

        private string areaToField;

        private decimal dateInvField;

        private bool dateInvFieldSpecified;

        private string currencyField;

        private decimal dateCeaseField;

        private bool dateCeaseFieldSpecified;

        private decimal dateEffectiveField;

        private bool dateEffectiveFieldSpecified;

        private string directIndField;

        private string idCaptureField;

        private string idModifyField;

        private decimal minChargeField;

        private bool minChargeFieldSpecified;

        private GetAccountRateListResponseAccountRateOutputRatesTable[] ratesTablesField;

        private decimal uniqueIdField;

        private bool uniqueIdFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CompanyCode
        {
            get { return this.companyCodeField; }
            set { this.companyCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CustCode
        {
            get { return this.custCodeField; }
            set { this.custCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ServiceType
        {
            get { return this.serviceTypeField; }
            set { this.serviceTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string RateType
        {
            get { return this.rateTypeField; }
            set { this.rateTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string ProdType
        {
            get { return this.prodTypeField; }
            set { this.prodTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string AreaFrom
        {
            get { return this.areaFromField; }
            set { this.areaFromField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string AreaTo
        {
            get { return this.areaToField; }
            set { this.areaToField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal DateInv
        {
            get { return this.dateInvField; }
            set { this.dateInvField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateInvSpecified
        {
            get { return this.dateInvFieldSpecified; }
            set { this.dateInvFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Currency
        {
            get { return this.currencyField; }
            set { this.currencyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public decimal DateCease
        {
            get { return this.dateCeaseField; }
            set { this.dateCeaseField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCeaseSpecified
        {
            get { return this.dateCeaseFieldSpecified; }
            set { this.dateCeaseFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public decimal DateEffective
        {
            get { return this.dateEffectiveField; }
            set { this.dateEffectiveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateEffectiveSpecified
        {
            get { return this.dateEffectiveFieldSpecified; }
            set { this.dateEffectiveFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string DirectInd
        {
            get { return this.directIndField; }
            set { this.directIndField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string IdCapture
        {
            get { return this.idCaptureField; }
            set { this.idCaptureField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string IdModify
        {
            get { return this.idModifyField; }
            set { this.idModifyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public decimal MinCharge
        {
            get { return this.minChargeField; }
            set { this.minChargeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinChargeSpecified
        {
            get { return this.minChargeFieldSpecified; }
            set { this.minChargeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RatesTable",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetAccountRateListResponseAccountRateOutputRatesTable[] RatesTables
        {
            get { return this.ratesTablesField; }
            set { this.ratesTablesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public decimal UniqueId
        {
            get { return this.uniqueIdField; }
            set { this.uniqueIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UniqueIdSpecified
        {
            get { return this.uniqueIdFieldSpecified; }
            set { this.uniqueIdFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB")]
    public partial class GetAccountRateListResponseAccountRateOutputRatesTable
    {

        private decimal bandOrderField;

        private bool bandOrderFieldSpecified;

        private decimal qtyFromField;

        private bool qtyFromFieldSpecified;

        private decimal qtyToField;

        private bool qtyToFieldSpecified;

        private decimal rateField;

        private bool rateFieldSpecified;

        private string rateIndField;

        private decimal rateIndAmtField;

        private bool rateIndAmtFieldSpecified;

        private string roundIndField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public decimal BandOrder
        {
            get { return this.bandOrderField; }
            set { this.bandOrderField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BandOrderSpecified
        {
            get { return this.bandOrderFieldSpecified; }
            set { this.bandOrderFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal QtyFrom
        {
            get { return this.qtyFromField; }
            set { this.qtyFromField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtyFromSpecified
        {
            get { return this.qtyFromFieldSpecified; }
            set { this.qtyFromFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public decimal QtyTo
        {
            get { return this.qtyToField; }
            set { this.qtyToField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtyToSpecified
        {
            get { return this.qtyToFieldSpecified; }
            set { this.qtyToFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public decimal Rate
        {
            get { return this.rateField; }
            set { this.rateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified
        {
            get { return this.rateFieldSpecified; }
            set { this.rateFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string RateInd
        {
            get { return this.rateIndField; }
            set { this.rateIndField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal RateIndAmt
        {
            get { return this.rateIndAmtField; }
            set { this.rateIndAmtField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateIndAmtSpecified
        {
            get { return this.rateIndAmtFieldSpecified; }
            set { this.rateIndAmtFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string RoundInd
        {
            get { return this.roundIndField; }
            set { this.roundIndField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAccountRateList",
        WrapperNamespace = "urn:com-softwareag-entirex-rpc:FWV6WEB", IsWrapped = true)]
    public partial class GetAccountRateListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InUserid;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InPassword;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InCustCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InRequestCtr;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IoSessionData;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetAccountRateListSequence Sequence;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 6)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetAccountRateListStartValues StartValues;

        public GetAccountRateListRequest()
        {
        }

        public GetAccountRateListRequest(string InUserid, string InPassword, string InCustCode, string InRequestCtr,
            string IoSessionData, GetAccountRateListSequence Sequence, GetAccountRateListStartValues StartValues)
        {
            this.InUserid = InUserid;
            this.InPassword = InPassword;
            this.InCustCode = InCustCode;
            this.InRequestCtr = InRequestCtr;
            this.IoSessionData = IoSessionData;
            this.Sequence = Sequence;
            this.StartValues = StartValues;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAccountRateListResponse",
        WrapperNamespace = "urn:com-softwareag-entirex-rpc:FWV6WEB", IsWrapped = true)]
    public partial class GetAccountRateListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IoSessionData;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCtr;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnMessage;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:com-softwareag-entirex-rpc:FWV6WEB",
            Order = 4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountRateOutput",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetAccountRateListResponseAccountRateOutput[] AccountRateOutputs;

        public GetAccountRateListResponse()
        {
        }

        public GetAccountRateListResponse(string IoSessionData, string ReturnCtr, string ReturnCode,
            string ReturnMessage, GetAccountRateListResponseAccountRateOutput[] AccountRateOutputs)
        {
            this.IoSessionData = IoSessionData;
            this.ReturnCtr = ReturnCtr;
            this.ReturnCode = ReturnCode;
            this.ReturnMessage = ReturnMessage;
            this.AccountRateOutputs = AccountRateOutputs;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface FWV6WEBPortChannel : FWV6WEBPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class FWV6WEBPortClient : System.ServiceModel.ClientBase<FWV6WEBPort>, FWV6WEBPort
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint,
            System.ServiceModel.Description.ClientCredentials clientCredentials);

        public FWV6WEBPortClient(EndpointConfiguration endpointConfiguration) :
            base(FWV6WEBPortClient.GetBindingForEndpoint(endpointConfiguration),
                FWV6WEBPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public FWV6WEBPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(FWV6WEBPortClient.GetBindingForEndpoint(endpointConfiguration),
                new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public FWV6WEBPortClient(EndpointConfiguration endpointConfiguration,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(FWV6WEBPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public FWV6WEBPortClient(System.ServiceModel.Channels.Binding binding,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<GetAccountRateListResponse> GetAccountRateListAsync(
            GetAccountRateListRequest request)
        {
            return base.Channel.GetAccountRateListAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginOpen(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginClose(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP12Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement =
                    new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(
                    System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement =
                    new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }

            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP11Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP12Port))
            {
                return new System.ServiceModel.EndpointAddress(
                    "http://triton-fw.clients.dovetail.co.za:8080/FreightWareV6/services/GetAccoun" +
                    "tRateList.FWV6WEBSOAP12Port/");
            }

            if ((endpointConfiguration == EndpointConfiguration.FWV6WEBSOAP11Port))
            {
                return new System.ServiceModel.EndpointAddress(
                    "http://triton-fw.clients.dovetail.co.za:8080/FreightWareV6/services/GetAccoun" +
                    "tRateList.FWV6WEBSOAP11Port/");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            FWV6WEBSOAP12Port,

            FWV6WEBSOAP11Port,
        }
    }
}